# Server Configuration
server.port=8083
spring.application.name=frontrest

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/expensedb?createDatabaseIfNotExist=true
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect